import Head from "next/head";
import React from "react";
import Layout from "../components/Layout";

const WorkshopsPage = () => {
  return (
    <Layout>
      <Head>
        <title>Anna Golińska Dietetyk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Warsztaty dietetyczne</h1>
      <p>Nie bez kozery jest przysłowie, przed żołądek do serca.</p>
      <p>
        Bo jak badania pokazują zdrowe jelita, to nie tylko zdrowe fizyczne ale
        również psychiczne.
      </p>
      <p>A każdy pracodawca kocha sowich pracowników</p>
      <p>Więc jak zadbać o te jelita?</p>
      <p>Jedzeniem.</p>
      <p>Tylko jakim?</p>
      <p>Warsztat dietetyczny, pomoże ustalić fakty i obalić mity.</p>
      <p>To inwestycja która przyniesie tylko korzyści.</p>
      <p>
        Już zmiana kilku nawyków zdrowotnych może pozytywnie zmienić wydajność
        zespołu.
      </p>
      <p>Podczas warsztatu zapewniam wesołą atmosferę.</p>
      <p>Wiedza, którą oferuję jest oparta na dowodach naukowych.</p>
      <p>Temat indywidualnie dopasuje do danej firmy.</p>
      <p>Zajęcia mogą odbyć się online albo na żywo.</p>
      <p>Standardowy czas trwania warsztatu to 90 minut.</p>
      <p>Propozycje warsztatów:</p>
      <p>
        I Zasady skutecznego odchudzania: Dlaczego nie mogę schudnąć? jak
        działać żeby nie było efektu jojo? Dlaczego diety nie działają?
      </p>
      <p>
        II warsztat &ndash; wiem co kupuję i jak przechowywać żywność &ndash;
        podczas warsztatu dowiemy się jak czytać etykiety? na co zwracać uwagę,
        podczas codziennych zakupów? Poruszamy również temat przechowywanie
        żywności aby jak najdłużej zachowała swoje właściwości. Warsztat
        przeznaczony dla kobiet, które mają dosyć wyrzucania jedzenia oraz chcą
        świadomie dokonywać zakupów. Co zyskasz: wiedzę i praktyczne wskazówki.
      </p>
      <p>
        III warsztat - analiza składu masy ciała przy użyciu wagi Tanita,
        dokładne omówienie wyników. Ustalenie swojego dziennego zapotrzebowania
        kalorycznego.
      </p>
      <p>
        IV warsztat- odporność – jak wspomóc się w czasie pandemii? Co jeść żeby
        być zdrowszym? Czy suplementować probiotyki?
      </p>
    </Layout>
  );
};

export default WorkshopsPage;
